apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: praveens-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - www.praveens.online
    secretName: praveens-online-tls
  rules:
  - host: www.praveens.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
